### ISSUE TITLE
crash on crafting

### ISSUE THREAD

**Issue by kevindevm** [rawii22/ChestInclusionForCrafting#1]
https://i.imgur.com/ktiolrp.jpeg cant repoduce out of this wolrd

**Comment by Ethan0429** [comment]
I've also experienced this bug. 

Steps to reproduce (AFAIK):
- Gather material to craft an item
- Craft desired item using at least one material from within your inventory (not inside of chests)
- Note: You do not have to be within chest proximity

It seems this crash only occurs on some worlds that fit a certain criteria (world length or something?) And the items crafted that cause the crash are completely random(?) For instance, a world of mine 146 days only appears to crash when I attempt to craft a chest (though the traceback shows it's this mod causing it). But the opener of this issue appears to crash when they attempt to craft an alchemy engine. I've seen another crash when trying to craft potted succulents as well. As I said, it seems pretty random, but it stays consistent to that world.
There might be other criteria to reproduce the bug, but it's really quite elusive.

I've found that removing the PushEvent("itemlose") altogether fixes the issue, however I believe this may(?) cause some sort of continuity issue between server clients.

Edit: 
I've also found that the bug does not occur if you're playing locally as opposed to online.

**Comment by rawii22** [comment]
Fun idea, could you send me a copy of that world? The whole cluster folder in Documents\Klei\DoNotStarveTogether\254404980

**Comment by Ethan0429** [comment]
> Fun idea, could you send me a copy of that world? The whole cluster folder in Documents\Klei\DoNotStarveTogether\254404980

Absolutely. Here is the cluster:
https://drive.google.com/file/d/1JMgm5wNnFfrW13r9nJXiWEdhysheuHMw/view?usp=sharing
Here are the server mods I'm using as well, in case that is helpful:
- Beefalo Widget
- Chest Includer
- Don't Reset World
- Entity Global Icon Indicator
- Finder Redux
- Global Positions

**Comment by rawii22** [comment]
We were finally able to reproduce the error on our own. It's a client thing. When clients (**including** hosts on worlds with caves) attempt to craft certain things from a container, the client will crash. There are also a few more mistakes we made that will require some extra fixing (refer to the example I made on my steam comment). ...... we'll let you know how this goes as we fix it.....

**Comment by rawii22** [comment]
We fixed all the issues people were having (theoretically)... The free crafting issue and the "data" crash. Test it out and let us know if it works!

**Comment by kevindevm** [comment]
fixed
