### ISSUE TITLE
crash on load from rollback (no host but admin)

### ISSUE THREAD

**Issue by kevindevm** [rawii22/ChestInclusionForCrafting#4]
[02:23:39]: [string "../mods/workshop-2168673904/modmain.lua"]:111: attempt to index field 'player_classified' (a nil value)
LUA ERROR stack traceback:
../mods/workshop-2168673904/modmain.lua:111 in () ? (Lua) <106-119>
   inst = 100087 - inventory_classified (valid:true)
   item = cutgrass
   amount = 3
   runoriginal = nil
   num_left_to_find = -567
=(tail call):-1 in ()  (tail) <-1--1>
../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:240 in (method) UpdateData (Lua) <197-269>
   self =
      frame_focused = Image - images/frontend_redux.xml:achievement_backing_hover.tex
      callbacks = table: 000000011CFEDFF0
      recipe = table: 0000000011E33AC0
      itemicon = Image - images/inventoryimages2.xml:rope.tex
      inst = 101720 -  (valid:true)
      focus = false
      skin = rope
      next_in_tab_order = FR_Entry
      children = table: 000000011CFED910
      parent = GRID
      focus_flow_args = table: 000000011CFED190
      focus_target = false
      ongainfocusfn = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:31
      ingredient_widgets = table: 00000000157FF3F0
      root = root
      onrightclick = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:72
      shown = true
      can_fade_alpha = true
      techicon = Image - images/inventoryimages2.xml:researchlab.tex
      enabled = true
      name = FR_Entry
      buffercheck = Image - ../mods/workshop-2288863757/images/favrecipes_check.xml:favrecipes_check.tex
      focus_flow = table: 0000000049C40DA0
      frame = Image - images/frontend_redux.xml:achievement_backing.tex
      owner = 100152 - wanda (valid:true)
      onclick = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:68
   ing_offset = 40
   ing_scale = 0.55
   ing_width = 37
   recipe = table: 0000000011E33AC0
   builder = table: 0000000039C953B0
   inventory = table: 0000000039C94EB0
   knows = false
   buffered = false
   can_build = false
   tech_level = table: 000000009D674130
   can_prototype = false
   k = 1
   v = table: 0000000011E34420
   amount_needed = 3
../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:194 in (method) SetRecipe (Lua) <158-195>
   self =
      frame_focused = Image - images/frontend_redux.xml:achievement_backing_hover.tex
      callbacks = table: 000000011CFEDFF0
      recipe = table: 0000000011E33AC0
      itemicon = Image - images/inventoryimages2.xml:rope.tex
      inst = 101720 -  (valid:true)
      focus = false
      skin = rope
      next_in_tab_order = FR_Entry
      children = table: 000000011CFED910
      parent = GRID
      focus_flow_args = table: 000000011CFED190
      focus_target = false
      ongainfocusfn = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:31
      ingredient_widgets = table: 00000000157FF3F0
      root = root
      onrightclick = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:72
      shown = true
      can_fade_alpha = true
      techicon = Image - images/inventoryimages2.xml:researchlab.tex
      enabled = true
      name = FR_Entry
      buffercheck = Image - ../mods/workshop-2288863757/images/favrecipes_check.xml:favrecipes_check.tex
      focus_flow = table: 0000000049C40DA0
      frame = Image - images/frontend_redux.xml:achievement_backing.tex
      owner = 100152 - wanda (valid:true)
      onclick = function - ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:68
   recipe = table: 0000000011E33AC0
   skin = rope
   imagename = rope.tex
   atlasname = images/inventoryimages2.xml
   techicon = researchlab.tex
../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:40 in (field) update_fn (Lua) <37-44>
   context = table: 000000011CFEB930
   widget = FR_Entry
   data = table: 000000011C6DEB40
   index = 1
../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:87 in (method) UpdateRecipes (Lua) <82-91>
   self =
      enabled = true
      focus_target = false
      parent = tl_scale_root
      focus_flow_args = table: 000000011CFE6520
     
[02:23:40]: [string "../mods/workshop-2168673904/modmain.lua"]:111: attempt to index field 'player_classified' (a nil value)
LUA ERROR stack traceback:
    ../mods/workshop-2168673904/modmain.lua:111 in () ? (Lua) <106-119>
    =(tail call):-1 in ()  (tail) <-1--1>
    ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:240 in (method) UpdateData (Lua) <197-269>
    ../mods/workshop-2288863757/scripts/widgets/favrecipes_entry.lua:194 in (method) SetRecipe (Lua) <158-195>
    ../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:40 in (field) update_fn (Lua) <37-44>
    ../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:87 in (method) UpdateRecipes (Lua) <82-91>
    ../mods/workshop-2288863757/scripts/widgets/favrecipes_list.lua:20 in (local) fn (Lua) <19-21>
    scripts/entityscript.lua:1112 in (method) PushEvent (Lua) <1099-1126>
    ../mods/workshop-2168673904/scripts/components/remoteinventory.lua:81 in (method) Refresh (Lua) <75-84>
    ../mods/workshop-2168673904/scripts/components/remoteinventory.lua:9 in (upvalue) OnUpdateCheck (Lua) <3-12>
    ../mods/workshop-2168673904/scripts/components/remoteinventory.lua:25 in (field) onupdatecheck (Lua) <25-25>
    ../mods/workshop-2168673904/scripts/components/remoteinventory.lua:71 in (method) ForceUpdate (Lua) <69-73>
    ../mods/workshop-2168673904/scripts/components/remoteinventory.lua:61 in (method) OnEntityWake (Lua) <59-62>
    scripts/mainfunctions.lua:632 in () ? (Lua) <606-636>

**Comment by kevindevm** [comment]
so for more info i have backpack extra slot and i got a backpack and also the [armour backpack from hamlet vortex cloak](https://dontstarve.fandom.com/wiki/Vortex_Cloak)

**Comment by rawii22** [comment]
Are you using this mod in Don’t Starve with the Hamlet DLC? This mod only works in Don’t Starve Together.
Also, are you trying to say this was in a dedicated server that someone else was hosting and you decided to rollback? (Did the whole server crash or was it just you?) In which case, did you have mods enabled to add the backpack equip slot and to add the vortex cloak to DST?

**Comment by kevindevm** [comment]
so no, im playing with[ tropical experience](https://steamcommunity.com/sharedfiles/filedetails/?id=1505270912) that does bring back hamlet and shipwrecked 
the server was a normal server hosted by other so 2 in the server me and the host , i am admin in the server too it only crashed me it crash sometimes tho, i cant reproduce sometimes when traveling with wanda backtrek or when rollback
also can be an error with ur mod that ignore the skin selected to craft?
